frontend/blog/forms.py
from flask_wtf import FlaskForm as Form
from flask_wtf import recaptcha
from wtforms import StringField, BooleanField, TextAreaField
from wtforms.validators import DataRequired, Length


class PostForm(Form):
    title = StringField('Titulo', [DataRequired(), Length(min=8)])
    content = TextAreaField("Contenido", [DataRequired(), Length(min=30)])
    tags = StringField("Etiquetas", [DataRequired(), Length(min=5, max=150)])


class CommentForm(Form):
    content = TextAreaField('Comentario', [DataRequired()])

frontend/blog/__init__.py
def create_module(app):
    from .controllers import blog_blueprint

    app.register_blueprint(blog_blueprint)

frontend/blog/controllers.py
import datetime
from werkzeug.local import LocalProxy
import requests
from flask_login import login_required
from flask import (Blueprint,
                   redirect,
                   url_for,
                   flash,
                   render_template,
                   request, current_app,
                   session,)

from ..auth import current_user, has_role, AnonymousUser
from ..auth.models import User
from .forms import CommentForm, PostForm


blog_blueprint = Blueprint(
    'blog',
    __name__,
    url_prefix='/blog',
    template_folder='../templates/blog',
    static_folder='../static/'
)

logger = LocalProxy(lambda: current_app.logger)

def side_bar():
    """Aqui buscamos las etiquetas mas usadas y los post mas recientes
    desde la api"""
    pass


@blog_blueprint.route('/', methods=['GET'])
def blog_home():
    data = requests.get('http://blog:5000/api')
    contenido = data.json()
    logger.info(contenido)
    now = datetime.datetime.now()
    return render_template('home.html',
                           contenido=contenido,
                           now=now,)


@blog_blueprint.route('/<post_id>', methods=['GET', 'POST'])
def ver_blog(post_id):
    form = CommentForm()
    if form.validate_on_submit():
        if current_user.is_authenticated:
            data = {'user': str(current_user.id), 'comment': form.content.data}
            url = f'http://blog:5000/api/comment/{post_id}'
            response = requests.post(url, json=data)
            return redirect(url_for('.ver_blog', post_id=post_id))

        flash('Debes estar logeado para poder comentar.', category='info')
        return redirect(url_for('.ver_blog', post_id=post_id))

    data = requests.get(f'http://blog:5000/api/{post_id}')
    contenido = data.json()
    if contenido.get('post'):
        session['contenido'] = contenido
        print('********** aqui el contenido', contenido)
        return render_template('post.html',
                               contenido=contenido,
                               form=form, post_id=post_id)

    flash('Post no encontrado', category='danger')
    return redirect(url_for('.blog_home'))


@blog_blueprint.route('/crea_post', methods=['GET', 'POST'])
@login_required
@has_role('poster')
def crea_post():
    """Al postear en la raiz creamos una nueva entrada en el blog
    para que sea funcional recuerda colocar el login_required, has_role
    y tambien enviarlo a la api blog"""

    form = PostForm()
    if form.validate_on_submit():
        data = {'title': form.title.data,
                'content': form.content.data,
                'tags': form.tags.data,
                'user': str(current_user.id)}
        url = 'http://blog:5000/api'
        response = requests.post(url, json=data)
        data_response = response.json()
        if 'post_id' in data_response:
            logger.info(data_response)
            flash(data_response['mensaje'], category='success')
            return redirect(url_for('.ver_blog',
                                    post_id=data_response['post_id']))
    flash('Aqui puedes crear tus Post.', category='info')
    return render_template('crea_post.html',
                           form=form)


@blog_blueprint.route('/edit/<post_id>', methods=['GET', 'POST'])
@login_required
def edit_blog(post_id):
    """Aqui capturas las modificAciones Al Blog En Un Json Y Lo Envias 
    De Vuelta A La Api Para Que Actualice La Base De Datos"""
    form = PostForm()
    if request.method == 'POST' and form.validate():
        data = {'title': form.title.data,
                'content': form.content.data,
                'tags': form.tags.data,
                'user': str(current_user.id)}
        url = f'http://blog:5000/api/{post_id}'
        response = requests.put(url, json=data)
        data_response = response.json()
        flash(data_response['mensaje'], category='success')
        return redirect(url_for('.ver_blog',
                                post_id=data_response['post_id']))

    data = requests.get(f'http://blog:5000/api/{post_id}')
    blog = data.json()
    form.title.data = blog['post']['title']
    form.content.data = blog['post']['content']
    form.tags.data = ','.join(blog['post']['tags'])
    if current_user.username == blog['username']:
        flash('Puedes comenzar a editar tu post.', category='info')
        return render_template(
            'edit_post.html',
            form=form,
            post_id=post_id)
    flash('Solo los autores de los sus post pueden editarlos.', category="danger")
    return redirect(url_for(".blog_home"))


@blog_blueprint.route('/delete/<blog_id>', methods=['GET'])
@login_required
@has_role('poster')
def delete_blog(blog_id):
    """Aqui capturas las modificaciones al blog en un json y lo envias 
    de vuelta a la api para que actualice la base de datos"""
    if current_user.is_authenticated:
        if current_user.username == session.get(
                'contenido').get('username') or current_user.has_role('admin'):
            
            userid = str(current_user.id)
            roles = []
            for role in current_user.roles:
                roles.append(role.nombre)
                data = {'userid': userid, 'roles': roles}
                url = f'http://blog:5000/api/{blog_id}'
                del_resp = requests.delete(url, json=data)
                respuesta = del_resp.json()
                print(respuesta)
                flash(respuesta['mensaje'], category='alert')
                return redirect(url_for('.blog_home'))
    flash('No se puede eliminar posts si no eres el propietario del post',
          category='danger')
    return redirect(url_for('.blog_home'))


@blog_blueprint.route('/tag/<tag_name>')
def busca_etiquetas(tag_name):
    url = f'http://blog:5000/api/tag/{tag_name}'
    data = requests.get(url)
    contenido = data.json()
    now = datetime.datetime.now()
    if contenido.get('posts'):
        flash(
            f'Etiqueta "{tag_name}" encontrada, estos son las entradas con esa etiqueta.', category="success")
        return render_template('home.html',
                               contenido=contenido,
                               now=now,)
    flash('Tag no encontrada', category="danger")
    return redirect(url_for('.blog_home'))


@blog_blueprint.route('/user/<user_name>')
def user_post(user_name):
    user = User.objects(username=user_name).first()
    if user:
        url = f'http://blog:5000/api/user/{str(user.id)}'
        data = requests.get(url)
        contenido = data.json()
        now = datetime.datetime.now()
        if contenido.get('posts'):
            flash(
                f'Usuario "{user_name}" encontrado, estos son los post de este usuario', category="success")
            return render_template('home.html',
                                   contenido=contenido,
                                   now=now,)
        flash('Publicacion de usuario no encontrada.', category="danger")
        return redirect(url_for('.blog_home'))

frontend/templates/blog/blognavbar.html
{% if current_user.is_authenticated %}
{% if current_user.has_role(['poster', 'admin']) %}
<nav class="owner-options">
  <a href="{{ url_for('blog.crea_post') }}"> Nuevo </a>
  {% if contenido %}
  {% if request.url_rule.endpoint == "blog.ver_blog" %}
  {% if current_user.username == contenido.username or current_user.has_role('admin')%}
  <a href="{{ url_for('blog.edit_blog', post_id=post_id) }}"> Edit </a>
  <a href="{{ url_for('blog.delete_blog', blog_id=post_id) }}"> Delete </a>
  
  {% endif %}
  {% endif %}
  {% endif %}
  
</nav>
{% endif %}
{% endif %}

frontend/templates/blog/crea_post.html
{% extends "base.html" %}
{% block head %}
<link rel="stylesheet" type="text/css" href="/static/css/blog.css">
{% endblock %}
{% block body %}
<div class="crea-post">
<form method="POST" action="{{ url_for('.crea_post') }}">
  {{ form.hidden_tag() }}
  
<!-- caja de titulo de creacion de post   -->
  <div class="titulo">
    {{ form.title.label }}
    {% if form.title.errors %}
    {% for e in form.title.errors %}
    <p class="help-block">{{ e }} </p>
    {% endfor %}
    {% endif %}
    {{ form.title(_class="form-control")}}
  </div>
  
  <!-- caja de contenido de creacion de texto -->
  <div class="contenido">
    <!-- {{ form.content.label }} -->
    {% if form.content.errors %}
    {% for e in form.content.errors %}
    <p class="help-block">{{ e }} </p>
    {% endfor %}
    {% endif %}
    {{ form.content(id="editor", class_='form-control') }}
  </div>
  
  <!-- caja de etiquetas de temas de la creacion de posts -->
  <div class="tags">
    {{ form.tags.label }}
    {% if form.tags.errors %}
    {% for e in form.tags.errors %}
    <p class="help-block">{{ e }} </p>
    {% endfor %}
    {% endif %}
    {{ form.tags(_class="form-control")}}
  </div>
  <input type="submit" value="Crear">
</form>
</div>
{% block js %}
<script src="//cdn.ckeditor.com/4.4.7/standard/ckeditor.js">
</script>
<script>
    CKEDITOR.replace('editor');
</script>
{% endblock %}
{% endblock %}

frontend/templates/blog/edit_post.html
{% extends "base.html" %}
{% block head %}
<link rel="stylesheet" type="text/css" href="/static/css/blog.css">

{% endblock %}
{% block body %}
<div class="crea-post">
<form method="POST" action="{{ url_for('.edit_blog', post_id=post_id) }}">
   {{ form.hidden_tag() }}
  <div class="titulo">
    {{ form.title.label }}
    {% if form.title.errors %}
    {% for e in form.title.errors %}
    <p class="help-block">{{ e }}</p>
    {% endfor %}
    {% endif %}
    {{ form.title }}
  </div>

    <div class="contenido">
    {{ form.content.label }}
    {% if form.content.errors %}
    {% for e in form.content.errors %}
    <p class="help-block">{{ e }}</p>
    {% endfor %}
    {% endif %}
    {{ form.content(id="editor", class_='form-control') }}
    </div>

    <div class="tags">
    {{ form.tags.label }}
    {% if form.tags.errors %}
    {% for e in form.tags.errors %}
    <p class="help-block">{{ e }}</p>
    {% endfor %}
    {% endif %}
    {{ form.tags }}
      </div>
      
  <input type="submit" value="Editar Post">
</form>
</div>
{% block js %}
<script src="//cdn.ckeditor.com/4.4.7/standard/ckeditor.js">
</script>
<script>
    CKEDITOR.replace('editor');
</script>
{% endblock %}
{% endblock %}

frontend/templates/blog/header.html
<div class="cabezera"> <h1> Bienvenido {{ current_user.username | capitalize }} </h1></div>

frontend/templates/blog/home.html
{% extends "base.html" %}
{% block head %}
<link rel="stylesheet" type="text/css" href="/static/css/blog.css">

{% endblock %}
{% block body %}
{% include "blognavbar.html" %}
<div class="visual-body">

  
  <div class="visual-left">
  </div>
  
<div class="home-visual">
{% for post in contenido.posts %}
<div class="home-post">
  <a href="{{url_for('.ver_blog', post_id=post.id) }}" class="home-title"><h1>{{ post.title }}</h1>
 <p class="home-parrafo contenido">{{ post.content | truncate(120) | safe}}</p>
  <div class="home-tags-container">
    <a href="#" class="home-date">{{ post.date | truncate(20,True) }}</a>
  </a>
  <div>
  {% for tag in post.tags %}<a href="{{ url_for('.busca_etiquetas', tag_name=tag) }}" class="home-tag">{{ tag | capitalize }}</a> 
    {% endfor %}
  </div>
</div>
 
  </div>
{% endfor %}

</div>

<div class="visual-right">
<div class="titulo">
    <h3>Post Recientes</h3>
  </div>  
<div class="posts-recientes">
  {% if contenido.sidebar %}
    {% for post in contenido.sidebar['posts'] %}
    <a href="{{ url_for('.ver_blog', post_id=post.id) }}" > {{ post.title }}</a>
    {% endfor %}
  </div>
<div class="titulo">
       <h3>Tags</h3>
    </div>
  <div class="tags-usados">
    
    {% for tag in contenido.sidebar.tags %}     
    <a href="{{ url_for('.busca_etiquetas', tag_name=tag) }}" class="home-tag"> <img src="/static/img/icon/tag.png" width="18"> {{ tag | capitalize }} ({{ contenido.sidebar.tags[tag]}})</a>
    {% endfor %}
    {% endif %}
  </div>
  
</div>
</div>


{% endblock %}

frontend/templates/blog/post.html
{% extends 'base.html' %}
{% block head %}
<link rel="stylesheet" type="text/css" href="/static/css/blog.css">

{% endblock %}
{% block body %}
{% include "blognavbar.html" %}
<div class="visual-body">
  <div class="visual-left">
  </div>
  <div class="post-central">
    <h1>{{ contenido.post.title }}</h1>
    <div class="descripcion">
    <small><a href="{{ url_for('.user_post', user_name=contenido.username) }}">{{ contenido.username }}</a></small>
    <small>- Hace {{ contenido.elapsed }} dias.</small></div>
    <div class="contenido">
    <p class="parrafadas">{{ contenido.post.content | safe}}</p>
    </div>
    <div class="tags">
    {% for tag in contenido.post.tags %}
    <a href="{{ url_for('.busca_etiquetas', tag_name=tag)}}">{{ tag }}</a>
    {% endfor %}
    </div>
    <div class="comentarios">
      
      <!-- Comienzo de el formulario de comentarios -->
      {% if current_user.is_authenticated %}
      <form method="POST" action="#">
	{{ form.hidden_tag() }}
	<div>
	  <p>{{ form.content.label }}</p>
	  {% if form.content.errors %}
	  {% for error in form.content.errors %}
	  <p class="help-block"> {{ error }} </p>
	  {% endfor %}
	  {% endif %}
	  {{ form.content(class_='form-control') }}
	</div>
	<input type="submit" value="Comentar">
      </form>
      {% else %}
      <h4> Para dejar un comentario Inicia Session <a href="{{ url_for('auth.login') }}">Log</a>
      </h4>
      {% endif %}
      <!-- Fin del Formulario de comentarios -->
      
      
      <!-- Aqui comienzan los comentarios -->
      <p class="comentarios"><small>{{ contenido.comments | length }}</small> Comentarios</p>
      {% for comment in contenido.comments %}
      <div class="comment">
	<p class="c-username">{{ comment.username }}</p>
	<p class="c-date"> Hace {{ comment.date }} dias.
	  
	  <!-- si el usuario actual es el mismo autor del comentario agrega link de editar-->
	  {% if comment.userid == current_user.id |string  %}
	  <a href="#">Edit</a>
	  {% endif %}
	</p>
	
	<p class="c-comment">{{ comment.comment }}</p>
      </div>
      {% endfor %}
      <!-- Aqui acaban los comentario -->

      
    </div>
  </div>
  <!-- Comienzo de la barra lateral -->
  <div class="visual-right">
    <div class="titulo">
      <h3>Post Recientes</h3>
    </div>  
    <div class="posts-recientes">
      {% for post in contenido.sidebar['posts'] %}
      <a href="{{ url_for('.ver_blog', post_id=post.id) }}" > {{ post.title }}</a>
      {% endfor %}
    </div>
    <div class="titulo">
      <h3>Tags</h3>
    </div>
    <div class="tags-usados">
      
      {% for tag in contenido.sidebar.tags %}     
      <a href="{{ url_for('.busca_etiquetas', tag_name=tag) }}" class="home-tag"> <img src="/static/img/icon/tag.png" width="18"> {{ tag | capitalize }} ({{ contenido.sidebar.tags[tag]}})</a>
      {% endfor %}
    </div>
    
  </div>
</div>
{% endblock %}