frontend/alquiler/controllers.py
import time
import qrcode
import datetime
from collections import Counter
import requests
from werkzeug.local import LocalProxy
import io
import jinja2
from flask_weasyprint import HTML, render_pdf
from flask_login import login_required
from flask import (Blueprint,
                   redirect,
                   url_for,
                   flash,
                   render_template,
                   request,
                   abort,
                   session,
                   send_file,
                   Response,
                   current_app, request_started,
                   )
from ..auth import current_user, has_role, AnonymousUser, has_roles
from ..auth.models import User
from .forms import (PropietarioForm, NotaForm,
                    ViviendaForm, InquilinoForm,
                    PagoForm, VisualForm)
from .procesa_datos import procesa_datos, proceso_pagos, mes
from .postproceso import owner, casa
from .tasks import send_mail
import json


alquiler_blueprint = Blueprint(
    'alquiler',
    __name__,
    url_prefix='/alquiler',
    template_folder='../templates/alquiler/',
    static_folder='../static/'
)

logger = LocalProxy(lambda: current_app.logger)


@alquiler_blueprint.before_request
def print_request():
    useragent = request
    logger.info(request.remote_addr)


def qr_generator(info):
    qr = qrcode.QRCode(
        version=1,
        error_correction=qrcode.constants.ERROR_CORRECT_L,
        box_size=5,
        border=4,
    )
    qr.add_data(info)
    qr.make(fit=True)
    img = qr.make_image(fill_color="black", back_color="white")
    with open('./frontend/static/img/qrcode.png', "wb") as f:
        img.save(f)


@alquiler_blueprint.route('/', methods=['GET'])
def admin_home():
    if current_user.is_authenticated:
        if current_user.has_role('admin'):
            flash('Usuario posee permisos de admin.')
            url = 'http://alquiler:5000/api/propietario'
            response = requests.get(url)
            mensaje = response.json()
            session['propietarios'] = mensaje.get('propietarios')

            return render_template('home_alquiler.html',
                                   propietarios=mensaje)

        elif current_user.has_role('gestor'):
            if current_user.gestiona:
                flash('Usuario posee propietarios que gestionar.')
                url = 'http://alquiler:5000/api/propietario'
                data = [{"_id": {"$oid": str(prop)}}
                        for prop in current_user.gestiona]
                response = requests.get(url, json=data)
                mensaje = response.json()
                session['propietarios'] = mensaje.get('propietarios')

                return render_template('home_alquiler.html',
                                       propietarios=mensaje)

            return render_template('home_alquiler.html', propietarios=True)

        elif current_user.has_role('propietario'):
            if current_user.gestiona:
                flash('usuario es propietario.', category="info")
                url = 'http://alquiler:5000/api/propietario'
                data = {"_id": {"$oid": str(current_user.gestiona[0])}}
                response = requests.get(url, json=data)
                mensaje = response.json()
                # logger.info(mensaje)
                session['propietarios'] = [mensaje.get('propietario')]

                return redirect(url_for('.ver_propietario', indice=0))
            flash('Usuario es propietario pero no tiene asignada ninguna propiedad.',
                  category="alert")
        return redirect(url_for("main.front_page"))
    else:
        flash("Usuaro para visualizacion.")
        return redirect(url_for('.inquilino_visualizacion'))


######################## Visualizacion Modelos #######################


@alquiler_blueprint.route('/propietatio/<indice>',
                          methods=['GET', 'POST'])
@login_required
@has_role(['admin', 'gestor', 'propietario'])
def ver_propietario(indice):
    """ Asumiendo que siempre se accede a  este endpoint desde home en caso 
    De que el que acceda sea el propietario optaremos por agregar directamente
    en el home_alquiler session['propietarios'] accediendo por indice nos 
    ahorramos mucha logica y podemos simplificar el endpoint"""
    nota_form = NotaForm()
    pago_form = PagoForm()

    if nota_form.validate_on_submit() and nota_form.comentario.data:
        contenido = f"<p>Comentario: {nota_form.comentario.data}</p>"
        usuario = f"<p>Usuario: {current_user.username}</p>"
        time_epoch = f'<p>Fecha: {time.strftime("%x %X")}</p>'
        string = " \n".join([usuario, time_epoch, contenido])
        propietario = session.get('propietario')
        data = {'propietario': propietario, 'nota': string}
        url = 'http://alquiler:5000/api/propietario'
        response = requests.put(url, json=data)
        mensaje = response.json()
        flash(mensaje.get('mensaje'), category="info")
        return redirect(url_for('.ver_propietario',
                                indice=session['prop_indice'],
                                nota_form=nota_form,
                                pago_form=pago_form))

    if pago_form.validate_on_submit() and pago_form.cantidad.data:
        cantidad = abs(pago_form.cantidad.data)
        mes = pago_form.mes.data
        forma_pago = pago_form.forma_pago.data
        nota = pago_form.nota.data or 'sin comentarios'
        propietario = session['propietario']
        data = {'cantidad': cantidad, 'mes': mes,
                'forma_pago': forma_pago, 'notas': nota,
                'propietario': propietario, 'pago': True,
                }
        url = 'http://alquiler:5000/api/propietario'
        response = requests.put(url, json=data)
        mensaje = response.json()
        usuario = current_user
        fecha = datetime.datetime.now()
        correos = [current_user.email, propietario['email']]
        pago = data
        texto = render_template('email_pago_propietario.html',
                                pago=data, usuario=usuario,
                                propietario=propietario, fecha=fecha)
        fecha = time.strftime("%x %X")
        info = f"""En fecha {fecha} 
se pago la cantidad de {formato_dinero(pago['cantidad'])}, 
de forma { pago['forma_pago']} por el mes de {nombre_mes(pago['mes'])},
a {propietario['nombre'] + ' ' + propietario['apellido']},
impreso por: '{current_user.username}'
       {fecha} 
San Cristobal, Republica Dominicana.  
        """
        qr_generator(info)
        for x in correos:
            data1 = {'correos': x, 'texto': texto}
            send_mail.delay(data1)
        # flash(mensaje.get('mensaje'), category="info")
        return redirect(url_for('.ver_propietario',
                                indice=session['prop_indice'],
                                nota_form=nota_form,
                                pago_form=pago_form))

    indice = int(indice)
    session['prop_indice'] = indice
    propietario = session['propietarios'][indice]
    session['propietario'] = propietario
    url = 'http://alquiler:5000/api/propietario'
    data = propietario
    response = requests.get(url, json=data, timeout=1)
    result = response.json()
    viviendas, notas, pagos, informacion, propietario = owner(result)
    pago_form.nota.data = "Sin comentarios."

    return render_template('home_alquiler.html',
                           propietario=propietario,
                           viviendas=viviendas,
                           nota_form=nota_form,
                           prop_indice=session['prop_indice'],
                           pago_form=pago_form,
                           informacion=informacion,)


@alquiler_blueprint.route('/vivienda/<indice>',
                          methods=['GET', 'POST'])
@login_required
@has_role(['admin', 'gestor', 'propietario'])
def ver_vivienda(indice):
    nota_form = NotaForm()
    if nota_form.validate_on_submit and nota_form.comentario.data:
        contenido = f"<p>Comentario: {nota_form.comentario.data}</p>"
        usuario = f"<p>Usuario: {current_user.username}</p>"
        time_epoch = f'<p>Fecha: {time.strftime("%x %X")}</p>'
        string = " \n".join([usuario, time_epoch, contenido])
        propietario = session.get('propietario')
        vivienda = session.get('viv_indice')
        data = {'propietario': propietario,
                'nota': string, 'vivienda': vivienda}

        url = 'http://alquiler:5000/api/vivienda'
        response = requests.post(url, json=data)
        mensaje = response.json()
        flash(mensaje.get('mensaje'), category="info")
        return redirect(url_for('.ver_vivienda',
                                indice=session['viv_indice'],
                                nota_form=nota_form,
                                ))
    indice = int(indice)
    propietario = session['propietario']
    vivienda = session['viviendas'][indice]
    url = 'http://alquiler:5000/api/vivienda'
    data = {'propietario': propietario, 'indice': indice}
    response = requests.get(url, json=data, timeout=1)
    resultado = response.json()

    session['viv_indice'] = indice
    informacion, vivienda, inquilino = casa(resultado)
    return render_template('vivienda.html',
                           vivienda=vivienda,
                           propietario=propietario,
                           inquilino=inquilino,
                           prop_indice=session.get('prop_indice'),
                           nota_form=nota_form,
                           informacion=informacion,
                           )


@alquiler_blueprint.route('/vivienda/inquilino/',
                          methods=['GET', 'POST'])
@login_required
@has_role(['admin', 'gestor', 'propietario'])
def ver_inquilino():
    form = PagoForm()

    if form.validate_on_submit():
        cantidad = abs(form.cantidad.data)
        mes = form.mes.data
        forma_pago = form.forma_pago.data

frontend/blog/controllers.py
import datetime
from werkzeug.local import LocalProxy
import requests
from flask_login import login_required
from flask import (Blueprint,
                   redirect,
                   url_for,
                   flash,
                   render_template,
                   request, current_app,
                   session,)

from ..auth import current_user, has_role, AnonymousUser
from ..auth.models import User
from .forms import CommentForm, PostForm


blog_blueprint = Blueprint(
    'blog',
    __name__,
    url_prefix='/blog',
    template_folder='../templates/blog',
    static_folder='../static/'
)

logger = LocalProxy(lambda: current_app.logger)

def side_bar():
    """Aqui buscamos las etiquetas mas usadas y los post mas recientes
    desde la api"""
    pass


@blog_blueprint.route('/', methods=['GET'])
def blog_home():
    data = requests.get('http://blog:5000/api')
    contenido = data.json()
    logger.info(contenido)
    now = datetime.datetime.now()
    return render_template('home.html',
                           contenido=contenido,
                           now=now,)


@blog_blueprint.route('/<post_id>', methods=['GET', 'POST'])
def ver_blog(post_id):
    form = CommentForm()
    if form.validate_on_submit():
        if current_user.is_authenticated:
            data = {'user': str(current_user.id), 'comment': form.content.data}
            url = f'http://blog:5000/api/comment/{post_id}'
            response = requests.post(url, json=data)
            return redirect(url_for('.ver_blog', post_id=post_id))

        flash('Debes estar logeado para poder comentar.', category='info')
        return redirect(url_for('.ver_blog', post_id=post_id))

    data = requests.get(f'http://blog:5000/api/{post_id}')
    contenido = data.json()
    if contenido.get('post'):
        session['contenido'] = contenido
        print('********** aqui el contenido', contenido)
        return render_template('post.html',
                               contenido=contenido,
                               form=form, post_id=post_id)

    flash('Post no encontrado', category='danger')
    return redirect(url_for('.blog_home'))


@blog_blueprint.route('/crea_post', methods=['GET', 'POST'])
@login_required
@has_role('poster')
def crea_post():
    """Al postear en la raiz creamos una nueva entrada en el blog
    para que sea funcional recuerda colocar el login_required, has_role
    y tambien enviarlo a la api blog"""

    form = PostForm()
    if form.validate_on_submit():
        data = {'title': form.title.data,
                'content': form.content.data,
                'tags': form.tags.data,
                'user': str(current_user.id)}
        url = 'http://blog:5000/api'
        response = requests.post(url, json=data)
        data_response = response.json()
        if 'post_id' in data_response:
            logger.info(data_response)
            flash(data_response['mensaje'], category='success')
            return redirect(url_for('.ver_blog',
                                    post_id=data_response['post_id']))
    flash('Aqui puedes crear tus Post.', category='info')
    return render_template('crea_post.html',
                           form=form)


@blog_blueprint.route('/edit/<post_id>', methods=['GET', 'POST'])
@login_required
def edit_blog(post_id):
    """Aqui capturas las modificAciones Al Blog En Un Json Y Lo Envias 
    De Vuelta A La Api Para Que Actualice La Base De Datos"""
    form = PostForm()
    if request.method == 'POST' and form.validate():
        data = {'title': form.title.data,
                'content': form.content.data,
                'tags': form.tags.data,
                'user': str(current_user.id)}
        url = f'http://blog:5000/api/{post_id}'
        response = requests.put(url, json=data)
        data_response = response.json()
        flash(data_response['mensaje'], category='success')
        return redirect(url_for('.ver_blog',
                                post_id=data_response['post_id']))

    data = requests.get(f'http://blog:5000/api/{post_id}')
    blog = data.json()
    form.title.data = blog['post']['title']
    form.content.data = blog['post']['content']
    form.tags.data = ','.join(blog['post']['tags'])
    if current_user.username == blog['username']:
        flash('Puedes comenzar a editar tu post.', category='info')
        return render_template(
            'edit_post.html',
            form=form,
            post_id=post_id)
    flash('Solo los autores de los sus post pueden editarlos.', category="danger")
    return redirect(url_for(".blog_home"))


@blog_blueprint.route('/delete/<blog_id>', methods=['GET'])
@login_required
@has_role('poster')
def delete_blog(blog_id):
    """Aqui capturas las modificaciones al blog en un json y lo envias 
    de vuelta a la api para que actualice la base de datos"""
    if current_user.is_authenticated:
        if current_user.username == session.get(
                'contenido').get('username') or current_user.has_role('admin'):
            
            userid = str(current_user.id)
            roles = []
            for role in current_user.roles:
                roles.append(role.nombre)
                data = {'userid': userid, 'roles': roles}
                url = f'http://blog:5000/api/{blog_id}'
                del_resp = requests.delete(url, json=data)
                respuesta = del_resp.json()
                print(respuesta)
                flash(respuesta['mensaje'], category='alert')
                return redirect(url_for('.blog_home'))
    flash('No se puede eliminar posts si no eres el propietario del post',
          category='danger')
    return redirect(url_for('.blog_home'))


@blog_blueprint.route('/tag/<tag_name>')
def busca_etiquetas(tag_name):
    url = f'http://blog:5000/api/tag/{tag_name}'
    data = requests.get(url)
    contenido = data.json()
    now = datetime.datetime.now()
    if contenido.get('posts'):
        flash(
            f'Etiqueta "{tag_name}" encontrada, estos son las entradas con esa etiqueta.', category="success")
        return render_template('home.html',
                               contenido=contenido,
                               now=now,)
    flash('Tag no encontrada', category="danger")
    return redirect(url_for('.blog_home'))


@blog_blueprint.route('/user/<user_name>')
def user_post(user_name):
    user = User.objects(username=user_name).first()
    if user:
        url = f'http://blog:5000/api/user/{str(user.id)}'
        data = requests.get(url)
        contenido = data.json()
        now = datetime.datetime.now()
        if contenido.get('posts'):
            flash(
                f'Usuario "{user_name}" encontrado, estos son los post de este usuario', category="success")
            return render_template('home.html',
                                   contenido=contenido,
                                   now=now,)
        flash('Publicacion de usuario no encontrada.', category="danger")
        return redirect(url_for('.blog_home'))

frontend/main/controller.py
from flask import Blueprint, render_template

main_blueprint = Blueprint(
    'main',
    __name__,
    url_prefix='/',
    template_folder='../templates/auth',
    static_folder='../static',)


@main_blueprint.route('/')
def front_page():
    return render_template('index.html')

frontend/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <script data-ad-client="ca-pub-3919034575489272" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    {% block head %}
    <link rel="stylesheet" type="text/css" href="/static/css/base.css">
    {% endblock %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block title %}
    <title>Maximo Tejeda</title>
    {% endblock %}
    </head>
  <body>
    {% include 'navbar.html' %}
    {% include 'blog/header.html' %}
    {% include 'message.html' %}
    {% block body %}
    {% endblock %}
    {% include "footer.html" %}
  </body>
  {% block js %}
{% endblock %}
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>    </body>
</html>
  </html>

frontend/templates/footer.html
<footer id="footer">
<div>
  <p class="pie">MaxsolInf 2020 </p>
  
  <a class= "pie emailto" href="mailto:maxsolinf@gmail.com"><img src="/static/img/icon/solicitud.png" width="50px"><br>Email-me</a>
</div>
<div class="social">
  
<a href="https://twitter.com/maxaltepo" class="redes"><img src="/static/img/icon/twitter.png" width="50px"></a>
<a href="https://www.facebook.com/maximoalessandry/" class="redes"><img src="/static/img/icon/facebook.png" width="50px"></a>
<a href="#" class="redes"><img src="/static/img/icon/instagram.png" width="50px"></a>
<a href="https://www.linkedin.com/in/maximo-alessandry-tejeda-pozo-89755449" class="redes"><img src="/static/img/icon/linkedin.png" width="50px"></a>
<a href="tel:18096602625" class="redes"><img src="/static/img/icon/contacto.png" width="50px"></a>

</div>

</footer>

frontend/templates/index.html
{% extends 'base.html' %}
{% block head %}
<link rel="stylesheet" type="text/css" href="/static/css/index.css">
{% endblock %}
{% block body %}
<div class="visual-body">
  <div class="opciones">
    <a href="{{ url_for('alquiler.admin_home')}}" class="alquiler">
      <div class="alquiler">
	<img src="/static/img/icon/alquiler.png" width=100px>
   
    <p>Alquilers</p>
    </div> </a>
    <a href="{{ url_for('blog.blog_home') }}" class="blog">
      <div class="blog">
	<img src="/static/img/icon/blog.png" width=100px>
    <p>Blog</p>
    </div>
     </a>
    <div class="ciudadanos">
      <p>Ciudadanos</p>
  </div>
  <div class="mapas">
    <p>Mapas</p>
  </div>
</div>
</div>

{% endblock %}

frontend/templates/message.html
{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
{% for category, message in messages %}
<div class="alert alert-{{ category }} alert-dismissible flashes" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    {{ message }}
</div>
{% endfor %}
{% endif %}
{% endwith %}

frontend/templates/navbar.html
<nav id="navegador">
  <div id="nav-left">
    <a href="{{ url_for('main.front_page')}}">Inicio</a>
    <a href="{{url_for('blog.blog_home') }}">Blog</a>
    {% if current_user.is_authenticated %}
    {% if current_user.has_role('admin') %}
    <a href="{{url_for('auth.administra')}}">Admin</a>
    {% endif %}
    {% endif %}
  </div>
  <div id="nav-right">
    {% if not current_user.is_authenticated %}
    <a href="{{ url_for('auth.login') }}" class="inicio">Login</a>
    {% endif %}
    {% if current_user.is_authenticated %}
    <a href="#" class="usuario">Usuario</a>
    <a href="{{ url_for('auth.logout') }}" class="fin">Fin Sesion</a>
    {% endif %}
    {% if not current_user.is_authenticated %}
    <a href="{{url_for('auth.register')}}" class="crea">Registrar</a>
    {% endif %}
  </div>
</nav>